-- TBL_TEXT_CLASSIFICATION_CLS
insert into TBL_TEXT_CLASSIFICATION_CLS (SEQNUM,REGDATE,CLASS) values (seq_text_classification_cls.nextval,sysdate,'undefined')
insert into TBL_TEXT_CLASSIFICATION_CLS (SEQNUM,REGDATE,CLASS) values (seq_text_classification_cls.nextval,sysdate,'fixlabel')
insert into TBL_TEXT_CLASSIFICATION_CLS (SEQNUM,REGDATE,CLASS) values (seq_text_classification_cls.nextval,sysdate,'fixvalue')
insert into TBL_TEXT_CLASSIFICATION_CLS (SEQNUM,REGDATE,CLASS) values (seq_text_classification_cls.nextval,sysdate,'entryrowlabel')
insert into TBL_TEXT_CLASSIFICATION_CLS (SEQNUM,REGDATE,CLASS) values (seq_text_classification_cls.nextval,sysdate,'entrycolumnlabel')
insert into TBL_TEXT_CLASSIFICATION_CLS (SEQNUM,REGDATE,CLASS) values (seq_text_classification_cls.nextval,sysdate,'entryvalue')

--TBL_TEXT_CLASSIFICATION_TRAIN
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'undefined','Voucher No')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'undefined','Voucher Date')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'undefined','4153 Korean Re')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'undefined','Proportional Treaty Statement')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'undefined','BV/HEO/2018/05/0626')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'undefined','01105/2018')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'fixlabel','Cedant')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'undefined','APEX')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'undefined','Partner of Choice')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'fixlabel','Class of Business')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'fixlabel','Period of Quarter')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'fixlabel','Period of Treaty')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'fixlabel','Our Reference')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'entryrowlabel','Currency')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'entryrowlabel','Premium')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'entryrowlabel','Commission')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'entryrowlabel','Claims')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'entryrowlabel','Reserve')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'entryrowlabel','Release')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'entryrowlabel','Interest')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'entryrowlabel','Brokerage')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'entryrowlabel','Portfolio')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'entryrowlabel','Balance')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'fixvalue',': Solidarity- First Insurance 2018')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'fixvalue',': Marine Cargo Surplus 2018')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'fixvalue','01-01-2018 TO 31-03-2018')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'fixvalue',': 01-01-2018 TO 31-12-2018')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'fixvalue',': APEX/BORD/2727')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'entryvalue','JOD 1.00')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'entryvalue','8347.70')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'entryvalue','3339.08')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'entryvalue','0.00')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'entryvalue','2504.31')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'entryvalue','0.00')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'entryvalue','0.00')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'entryvalue','208.69')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'entryvalue','0.00')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'entryvalue','2295.62')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'undefined','APEX INSURANCE')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'undefined','APEX')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'undefined','Partner of Choice')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'undefined','Voucher No')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'undefined','4153 Korean Re')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'undefined','Proportional Treaty Statement')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'undefined','BV/HEO/2018/05/0626')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'undefined','01105/2018')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'fixlabel','Cedant')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'fixlabel','Class of Business')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'fixlabel','Period of Quarter')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'fixlabel','Period of Treaty')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'fixlabel','Our Reference')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'entryrowlabel','Currency')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'entryrowlabel','Premium')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'entryrowlabel','Commission')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'entryrowlabel','Claims')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'entryrowlabel','Reserve')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'entryrowlabel','Release')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'entryrowlabel','Interest')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'entryrowlabel','Brokerage')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'entryrowlabel','Portfolio')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'entryrowlabel','Balance')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'fixvalue',': Solidarity- First Insurance 2018')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'fixvalue',': Marine Cargo Surplus 2018 - Inward')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'fixvalue','01-01-2018 TO 31-03-2018')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'fixvalue',': 01-01-2018 TO 31-12-2018')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'fixvalue',': APEX/BORD/2727')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'entryvalue','JOD 1.00')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'entryvalue','25.53')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'entryvalue','5.74')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'entryvalue','0.00')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'entryvalue','7.66')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'entryvalue','0.00')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'entryvalue','0.00')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'entryvalue','0.64')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'entryvalue','0.00')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'entryvalue','11 .49')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'undefined','APEX INSURANCE')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'fixvalue','CARGO Q/S & S/P')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'fixvalue','APEX/BORD/2727')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'fixvalue','Solidarity- First Insurance 2018')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'fixvalue','Marine Cargo Surplus 2018')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'fixvalue','01-01-2018 TO 31-12-2018')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'fixvalue','APEX/BORD/2727')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'fixvalue','Marine Cargo Surplus 2018 - Inward')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'fixvalue',': CARGO Q/S & S/P')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'undefined','APEX')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'undefined','Voucher No')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'fixlabel','Cedant')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'undefined','Partner of Choice')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'fixlabel','Class of Business')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'fixvalue',': Solidarity- First Insurance 2018')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'fixvalue',': Marine Cargo Surplus 2018 - Inward')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'undefined','Partner of Choice')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'undefined','Voucher No')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'fixlabel','Class of Business')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'undefined','APEX')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'fixlabel','Cedant')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'fixvalue',': Solidarity- First Insurance 2018')
insert into TBL_TEXT_CLASSIFICATION_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_text_classification_train.nextval,sysdate,'fixvalue',': Marine Cargo Surplus 2018 - Inward')

--TBL_LABEL_MAPPING_CLS
insert into TBL_LABEL_MAPPING_CLS (SEQNUM,REGDATE,CLASS) values (seq_label_mapping_cls.nextval,sysdate,'CSCO_NM')
insert into TBL_LABEL_MAPPING_CLS (SEQNUM,REGDATE,CLASS) values (seq_label_mapping_cls.nextval,sysdate,'CT_NM')
insert into TBL_LABEL_MAPPING_CLS (SEQNUM,REGDATE,CLASS) values (seq_label_mapping_cls.nextval,sysdate,'INS_ST_DT')
insert into TBL_LABEL_MAPPING_CLS (SEQNUM,REGDATE,CLASS) values (seq_label_mapping_cls.nextval,sysdate,'INS_END_DT')
insert into TBL_LABEL_MAPPING_CLS (SEQNUM,REGDATE,CLASS) values (seq_label_mapping_cls.nextval,sysdate,'CUR_CD')
insert into TBL_LABEL_MAPPING_CLS (SEQNUM,REGDATE,CLASS) values (seq_label_mapping_cls.nextval,sysdate,'PRE')
insert into TBL_LABEL_MAPPING_CLS (SEQNUM,REGDATE,CLASS) values (seq_label_mapping_cls.nextval,sysdate,'COM')
insert into TBL_LABEL_MAPPING_CLS (SEQNUM,REGDATE,CLASS) values (seq_label_mapping_cls.nextval,sysdate,'BRKG')
insert into TBL_LABEL_MAPPING_CLS (SEQNUM,REGDATE,CLASS) values (seq_label_mapping_cls.nextval,sysdate,'TXAM')
insert into TBL_LABEL_MAPPING_CLS (SEQNUM,REGDATE,CLASS) values (seq_label_mapping_cls.nextval,sysdate,'PRRS_CF')
insert into TBL_LABEL_MAPPING_CLS (SEQNUM,REGDATE,CLASS) values (seq_label_mapping_cls.nextval,sysdate,'PRRS_RLS')
insert into TBL_LABEL_MAPPING_CLS (SEQNUM,REGDATE,CLASS) values (seq_label_mapping_cls.nextval,sysdate,'LSRES_CF')
insert into TBL_LABEL_MAPPING_CLS (SEQNUM,REGDATE,CLASS) values (seq_label_mapping_cls.nextval,sysdate,'LSRES_RLS')
insert into TBL_LABEL_MAPPING_CLS (SEQNUM,REGDATE,CLASS) values (seq_label_mapping_cls.nextval,sysdate,'CLA')
insert into TBL_LABEL_MAPPING_CLS (SEQNUM,REGDATE,CLASS) values (seq_label_mapping_cls.nextval,sysdate,'EXEX')
insert into TBL_LABEL_MAPPING_CLS (SEQNUM,REGDATE,CLASS) values (seq_label_mapping_cls.nextval,sysdate,'SVF')
insert into TBL_LABEL_MAPPING_CLS (SEQNUM,REGDATE,CLASS) values (seq_label_mapping_cls.nextval,sysdate,'CAS')
insert into TBL_LABEL_MAPPING_CLS (SEQNUM,REGDATE,CLASS) values (seq_label_mapping_cls.nextval,sysdate,'NTBL')
insert into TBL_LABEL_MAPPING_CLS (SEQNUM,REGDATE,CLASS) values (seq_label_mapping_cls.nextval,sysdate,'UNDEFINED')
insert into TBL_LABEL_MAPPING_CLS (SEQNUM,REGDATE,CLASS) values (seq_label_mapping_cls.nextval,sysdate,'CSCO_SA_RFRN_CNNT2')

--TBL_LABEL_MAPPING_TRAIN
insert into TBL_LABEL_MAPPING_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_label_mapping_train.nextva,sysdate,'CSCO_NM','Cedant')
insert into TBL_LABEL_MAPPING_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_label_mapping_train.nextva,sysdate,'CT_NM','Class of Business')
insert into TBL_LABEL_MAPPING_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_label_mapping_train.nextva,sysdate,'INS_ST_DT','Period of Quarter')
insert into TBL_LABEL_MAPPING_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_label_mapping_train.nextva,sysdate,'INS_END_DT','Period of Treaty')
insert into TBL_LABEL_MAPPING_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_label_mapping_train.nextva,sysdate,'CSCO_SA_RFRN_CNNT2','Our Reference')
insert into TBL_LABEL_MAPPING_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_label_mapping_train.nextva,sysdate,'CUR_CD','Currency')
insert into TBL_LABEL_MAPPING_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_label_mapping_train.nextva,sysdate,'PRE','Premium')
insert into TBL_LABEL_MAPPING_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_label_mapping_train.nextva,sysdate,'COM','Commission')
insert into TBL_LABEL_MAPPING_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_label_mapping_train.nextva,sysdate,'CLA','Claims')
insert into TBL_LABEL_MAPPING_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_label_mapping_train.nextva,sysdate,'PRRS_CF','Reserve')
insert into TBL_LABEL_MAPPING_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_label_mapping_train.nextva,sysdate,'PRRS_RLS','Release')
insert into TBL_LABEL_MAPPING_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_label_mapping_train.nextva,sysdate,'EXEX','Interest')
insert into TBL_LABEL_MAPPING_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_label_mapping_train.nextva,sysdate,'BRKG','Brokerage')
insert into TBL_LABEL_MAPPING_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_label_mapping_train.nextva,sysdate,'SVF','Portfolio')
insert into TBL_LABEL_MAPPING_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_label_mapping_train.nextva,sysdate,'NTBL','Balance')
insert into TBL_LABEL_MAPPING_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_label_mapping_train.nextva,sysdate,'CSCO_NM','Cedant')
insert into TBL_LABEL_MAPPING_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_label_mapping_train.nextva,sysdate,'CT_NM','Class of Business')
insert into TBL_LABEL_MAPPING_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_label_mapping_train.nextva,sysdate,'INS_ST_DT','Period of Quarter')
insert into TBL_LABEL_MAPPING_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_label_mapping_train.nextva,sysdate,'INS_END_DT','Period of Treaty')
insert into TBL_LABEL_MAPPING_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_label_mapping_train.nextva,sysdate,'CSCO_SA_RFRN_CNNT2','Our Reference')
insert into TBL_LABEL_MAPPING_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_label_mapping_train.nextva,sysdate,'CUR_CD','Currency')
insert into TBL_LABEL_MAPPING_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_label_mapping_train.nextva,sysdate,'PRE','Premium')
insert into TBL_LABEL_MAPPING_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_label_mapping_train.nextva,sysdate,'COM','Commission')
insert into TBL_LABEL_MAPPING_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_label_mapping_train.nextva,sysdate,'CLA','Claims')
insert into TBL_LABEL_MAPPING_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_label_mapping_train.nextva,sysdate,'PRRS_CF','Reserve')
insert into TBL_LABEL_MAPPING_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_label_mapping_train.nextva,sysdate,'PRRS_RLS','Release')
insert into TBL_LABEL_MAPPING_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_label_mapping_train.nextva,sysdate,'EXEX','Interest')
insert into TBL_LABEL_MAPPING_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_label_mapping_train.nextva,sysdate,'BRKG','Brokerage')
insert into TBL_LABEL_MAPPING_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_label_mapping_train.nextva,sysdate,'SVF','Portfolio')
insert into TBL_LABEL_MAPPING_TRAIN (SEQNUM,REGDATE,CLASS,TEXT) values (seq_label_mapping_train.nextva,sysdate,'NTBL','Balance')

--TBL_EXTRACTION_KEYWORD
insert into TBL_EXTRACTION_KEYWORD (SEQNUM,LABEL,ENKEYWORD,KOKEYWORD) values (seq_extraction_keyword.nextval,'fixlabel','CSCO_NM','거래사명')
insert into TBL_EXTRACTION_KEYWORD (SEQNUM,LABEL,ENKEYWORD,KOKEYWORD) values (seq_extraction_keyword.nextval,'fixlabel','CT_NM','계약명')
insert into TBL_EXTRACTION_KEYWORD (SEQNUM,LABEL,ENKEYWORD,KOKEYWORD) values (seq_extraction_keyword.nextval,'fixlabel','INS_ST_DT','보험개시일')
insert into TBL_EXTRACTION_KEYWORD (SEQNUM,LABEL,ENKEYWORD,KOKEYWORD) values (seq_extraction_keyword.nextval,'fixlabel','INS_END_DT','보험종료일')
insert into TBL_EXTRACTION_KEYWORD (SEQNUM,LABEL,ENKEYWORD,KOKEYWORD) values (seq_extraction_keyword.nextval,'entryrowlabel','CUR_CD','화폐코드')
insert into TBL_EXTRACTION_KEYWORD (SEQNUM,LABEL,ENKEYWORD,KOKEYWORD) values (seq_extraction_keyword.nextval,'entryrowlabel','PRE','보험료')
insert into TBL_EXTRACTION_KEYWORD (SEQNUM,LABEL,ENKEYWORD,KOKEYWORD) values (seq_extraction_keyword.nextval,'entryrowlabel','COM','일반수수료')
insert into TBL_EXTRACTION_KEYWORD (SEQNUM,LABEL,ENKEYWORD,KOKEYWORD) values (seq_extraction_keyword.nextval,'entryrowlabel','BRKG','중개수수료')
insert into TBL_EXTRACTION_KEYWORD (SEQNUM,LABEL,ENKEYWORD,KOKEYWORD) values (seq_extraction_keyword.nextval,'entryrowlabel','TXAM','세금')
insert into TBL_EXTRACTION_KEYWORD (SEQNUM,LABEL,ENKEYWORD,KOKEYWORD) values (seq_extraction_keyword.nextval,'entryrowlabel','PRRS_CF','보험료유보금적립액')
insert into TBL_EXTRACTION_KEYWORD (SEQNUM,LABEL,ENKEYWORD,KOKEYWORD) values (seq_extraction_keyword.nextval,'entryrowlabel','PRRS_RLS','보험료유보금해제액')
insert into TBL_EXTRACTION_KEYWORD (SEQNUM,LABEL,ENKEYWORD,KOKEYWORD) values (seq_extraction_keyword.nextval,'entryrowlabel','CLA','보험금')
insert into TBL_EXTRACTION_KEYWORD (SEQNUM,LABEL,ENKEYWORD,KOKEYWORD) values (seq_extraction_keyword.nextval,'entryrowlabel','EXEX','부대비')
insert into TBL_EXTRACTION_KEYWORD (SEQNUM,LABEL,ENKEYWORD,KOKEYWORD) values (seq_extraction_keyword.nextval,'entryrowlabel','SVF','손해조사비')
insert into TBL_EXTRACTION_KEYWORD (SEQNUM,LABEL,ENKEYWORD,KOKEYWORD) values (seq_extraction_keyword.nextval,'entryrowlabel','CAS','즉시불보험금(CASH)')
insert into TBL_EXTRACTION_KEYWORD (SEQNUM,LABEL,ENKEYWORD,KOKEYWORD) values (seq_extraction_keyword.nextval,'entryrowlabel','NTBL','순평균')
insert into TBL_EXTRACTION_KEYWORD (SEQNUM,LABEL,ENKEYWORD,KOKEYWORD) values (seq_extraction_keyword.nextval,'fixlabel','CSCO_SA_RFRN_CNNT2','참고')
insert into TBL_EXTRACTION_KEYWORD (SEQNUM,LABEL,ENKEYWORD,KOKEYWORD) values (seq_extraction_keyword.nextval,'fixvalue','CSCO_NM_VALUE','거래사명 값')
insert into TBL_EXTRACTION_KEYWORD (SEQNUM,LABEL,ENKEYWORD,KOKEYWORD) values (seq_extraction_keyword.nextval,'fixvalue','CT_NM_VALUE','계약명 값')
insert into TBL_EXTRACTION_KEYWORD (SEQNUM,LABEL,ENKEYWORD,KOKEYWORD) values (seq_extraction_keyword.nextval,'fixvalue','INS_ST_DT_VALUE','보험개시일 값')
insert into TBL_EXTRACTION_KEYWORD (SEQNUM,LABEL,ENKEYWORD,KOKEYWORD) values (seq_extraction_keyword.nextval,'fixvalue','INS_END_DT_VALUE','보험종료일 값')
insert into TBL_EXTRACTION_KEYWORD (SEQNUM,LABEL,ENKEYWORD,KOKEYWORD) values (seq_extraction_keyword.nextval,'entryvalue','CUR_CD_VALUE','화폐코드 값')
insert into TBL_EXTRACTION_KEYWORD (SEQNUM,LABEL,ENKEYWORD,KOKEYWORD) values (seq_extraction_keyword.nextval,'entryvalue','PRE_VALUE','보험료 값')
insert into TBL_EXTRACTION_KEYWORD (SEQNUM,LABEL,ENKEYWORD,KOKEYWORD) values (seq_extraction_keyword.nextval,'entryvalue','COM_VALUE','일반수수료 값')
insert into TBL_EXTRACTION_KEYWORD (SEQNUM,LABEL,ENKEYWORD,KOKEYWORD) values (seq_extraction_keyword.nextval,'entryvalue','BRKG_VALUE','중개수수료 값')
insert into TBL_EXTRACTION_KEYWORD (SEQNUM,LABEL,ENKEYWORD,KOKEYWORD) values (seq_extraction_keyword.nextval,'entryvalue','TXAM_VALUE','세금 값')
insert into TBL_EXTRACTION_KEYWORD (SEQNUM,LABEL,ENKEYWORD,KOKEYWORD) values (seq_extraction_keyword.nextval,'entryvalue','PRRS_CF_VALUE','보험료유보금적립액 값')
insert into TBL_EXTRACTION_KEYWORD (SEQNUM,LABEL,ENKEYWORD,KOKEYWORD) values (seq_extraction_keyword.nextval,'entryvalue','PRRS_RLS_VALUE','보험료유보금해제액 값')
insert into TBL_EXTRACTION_KEYWORD (SEQNUM,LABEL,ENKEYWORD,KOKEYWORD) values (seq_extraction_keyword.nextval,'entryvalue','CLA_VALUE','보험금 값')
insert into TBL_EXTRACTION_KEYWORD (SEQNUM,LABEL,ENKEYWORD,KOKEYWORD) values (seq_extraction_keyword.nextval,'entryvalue','EXEX_VALUE','부대비 값')
insert into TBL_EXTRACTION_KEYWORD (SEQNUM,LABEL,ENKEYWORD,KOKEYWORD) values (seq_extraction_keyword.nextval,'entryvalue','SVF_VALUE','손해조사비 값')
insert into TBL_EXTRACTION_KEYWORD (SEQNUM,LABEL,ENKEYWORD,KOKEYWORD) values (seq_extraction_keyword.nextval,'entryvalue','CAS_VALUE','즉시불보험금(CASH) 값')
insert into TBL_EXTRACTION_KEYWORD (SEQNUM,LABEL,ENKEYWORD,KOKEYWORD) values (seq_extraction_keyword.nextval,'entryvalue','NTBL_VALUE','순평균 값')
insert into TBL_EXTRACTION_KEYWORD (SEQNUM,LABEL,ENKEYWORD,KOKEYWORD) values (seq_extraction_keyword.nextval,'fixvalue','CSCO_SA_RFRN_CNNT2_VALUE','참고 값')

--TBL_OCR_COMM_USER
insert into TBL_OCR_COMM_USER (SEQNUM,OCRUSECOUNT,LASTLOGINDATE,JOINDATE,EMAIL,AUTH,USERPW,USERID) values (seq_ocr_comm_user.nextval,'0','18/07/25 16:07:10.000000','18/07/23','admin@admin.com','','123','admin')

