alter table T_ASAMPLE_XLS rename column C_IMAGE_ID to IMGID;
alter table T_ASAMPLE_XLS modify (IMGID varchar2(110));
alter table T_ASAMPLE_XLS rename column C____ to PAGENUM;
alter table T_ASAMPLE_XLS modify (PAGENUM varchar2(110));
alter table T_ASAMPLE_XLS rename column C_____ to FILEPATH;
alter table T_ASAMPLE_XLS modify (FILEPATH varchar2(110));
alter table T_ASAMPLE_XLS rename column C_____1 to TOTALCOUNT;
alter table T_ASAMPLE_XLS modify (TOTALCOUNT varchar2(110));

alter table T_BSAMPLE_XLS rename column C_IMAGE_ID to IMGID;
alter table T_BSAMPLE_XLS modify (IMGID varchar2(110));
alter table T_BSAMPLE_XLS rename column C____FROM to IMGFILESTARTNO;
alter table T_BSAMPLE_XLS modify (IMGFILESTARTNO varchar2(110));
alter table T_BSAMPLE_XLS rename column C____TO to IMGFILEENDNO;
alter table T_BSAMPLE_XLS modify (IMGFILEENDNO varchar2(110));
alter table T_BSAMPLE_XLS rename column C_ENTRY_NO to ENTRYNO;
alter table T_BSAMPLE_XLS modify (ENTRYNO varchar2(110));
alter table T_BSAMPLE_XLS rename column C____ to STATEMENTDIV;
alter table T_BSAMPLE_XLS modify (STATEMENTDIV varchar2(110));
alter table T_BSAMPLE_XLS rename column C___ to CONTRACTNUM;
alter table T_BSAMPLE_XLS modify (CONTRACTNUM varchar2(110));
alter table T_BSAMPLE_XLS rename column C____1 to OGCOMPANYCODE;
alter table T_BSAMPLE_XLS modify (OGCOMPANYCODE varchar2(110));
alter table T_BSAMPLE_XLS rename column C___1 to OGCOMPANYNAME;
alter table T_BSAMPLE_XLS modify (OGCOMPANYNAME varchar2(110));
alter table T_BSAMPLE_XLS rename column C____2 to BROKERCODE;
alter table T_BSAMPLE_XLS modify (BROKERCODE varchar2(110));
alter table T_BSAMPLE_XLS rename column C___2 to BROKERNAME;
alter table T_BSAMPLE_XLS modify (BROKERNAME varchar2(110));
alter table T_BSAMPLE_XLS rename column C___3 to CTNM;
alter table T_BSAMPLE_XLS modify (CTNM varchar2(110));
alter table T_BSAMPLE_XLS rename column C____3 to INSSTDT;
alter table T_BSAMPLE_XLS modify (INSSTDT varchar2(110));
alter table T_BSAMPLE_XLS rename column C____4 to INSENDDT;
alter table T_BSAMPLE_XLS modify (INSENDDT varchar2(110));
alter table T_BSAMPLE_XLS rename column C_UY to UY;
alter table T_BSAMPLE_XLS modify (UY varchar2(110));
alter table T_BSAMPLE_XLS rename column C___4 to CURCD;
alter table T_BSAMPLE_XLS modify (CURCD varchar2(110));
alter table T_BSAMPLE_XLS rename column C_PAID_100_ to PAIDPERCENT;
alter table T_BSAMPLE_XLS modify (PAIDPERCENT varchar2(110));
alter table T_BSAMPLE_XLS rename column C_PAID_OUR_SHARE_ to PAIDSHARE;
alter table T_BSAMPLE_XLS modify (PAIDSHARE varchar2(110));
alter table T_BSAMPLE_XLS rename column C_OSL_100_ to OSLPERCENT;
alter table T_BSAMPLE_XLS modify (OSLPERCENT varchar2(110));
alter table T_BSAMPLE_XLS rename column C_OSL_OUR_SHARE_ to OSLSHARE;
alter table T_BSAMPLE_XLS modify (OSLSHARE varchar2(110));
alter table T_BSAMPLE_XLS rename column C_GROSS_PREMIUM to GROSSPM;
alter table T_BSAMPLE_XLS modify (GROSSPM varchar2(110));
alter table T_BSAMPLE_XLS rename column C_PREMIUM to PM;
alter table T_BSAMPLE_XLS modify (PM varchar2(110));
alter table T_BSAMPLE_XLS rename column C_PREMIUM_P_F_ENT to PMPFEND;
alter table T_BSAMPLE_XLS modify (PMPFEND varchar2(110));
alter table T_BSAMPLE_XLS rename column C_PREMIUM_P_F_WOS to PMPFWOS;
alter table T_BSAMPLE_XLS modify (PMPFWOS varchar2(110));
alter table T_BSAMPLE_XLS rename column C_XOL_PREMIUM to XOLPM;
alter table T_BSAMPLE_XLS modify (XOLPM varchar2(110));
alter table T_BSAMPLE_XLS rename column C_RETURN_PREMIUM to RETURNPM;
alter table T_BSAMPLE_XLS modify (RETURNPM varchar2(110));
alter table T_BSAMPLE_XLS rename column C_GROSS_COMMISSION to GROSSCN;
alter table T_BSAMPLE_XLS modify (GROSSCN varchar2(110));
alter table T_BSAMPLE_XLS rename column C_COMMISSION to CN;
alter table T_BSAMPLE_XLS modify (CN varchar2(110));
alter table T_BSAMPLE_XLS rename column C_PROFIT_COMMISSION to PROFITCN;
alter table T_BSAMPLE_XLS modify (PROFITCN varchar2(110));
alter table T_BSAMPLE_XLS rename column C_BROKERAGE to BROKERAGE;
alter table T_BSAMPLE_XLS modify (BROKERAGE varchar2(110));
alter table T_BSAMPLE_XLS rename column C_TAX to TAX;
alter table T_BSAMPLE_XLS modify (TAX varchar2(110));
alter table T_BSAMPLE_XLS rename column C_OVERRIDING_COM to OVERRIDINGCOM;
alter table T_BSAMPLE_XLS modify (OVERRIDINGCOM varchar2(110));
alter table T_BSAMPLE_XLS rename column C_CHARGE to CHARGE;
alter table T_BSAMPLE_XLS modify (CHARGE varchar2(110));
alter table T_BSAMPLE_XLS rename column C_PREMUIM_RESERVE_RTD to PMRESERVERTD1;
alter table T_BSAMPLE_XLS modify (PMRESERVERTD1 varchar2(110));
alter table T_BSAMPLE_XLS rename column C_P_F_PREMIUM_RESERVE_RTD to PFPMRESERVERTD1;
alter table T_BSAMPLE_XLS modify (PFPMRESERVERTD1 varchar2(110));
alter table T_BSAMPLE_XLS rename column C_PREMIUM_RESERVE_RLD to PMRESERVERTD2;
alter table T_BSAMPLE_XLS modify (PMRESERVERTD2 varchar2(110));
alter table T_BSAMPLE_XLS rename column C_P_F_PREMIUM_RESERVE_RLD to PFPMRESERVERTD2;
alter table T_BSAMPLE_XLS modify (PFPMRESERVERTD2 varchar2(110));
alter table T_BSAMPLE_XLS rename column C_CLAIM to CLAIM;
alter table T_BSAMPLE_XLS modify (CLAIM varchar2(110));
alter table T_BSAMPLE_XLS rename column C_LOSS_RECOVERY to LOSSRECOVERY;
alter table T_BSAMPLE_XLS modify (LOSSRECOVERY varchar2(110));
alter table T_BSAMPLE_XLS rename column C_CASH_LOSS to CASHLOSS;
alter table T_BSAMPLE_XLS modify (CASHLOSS varchar2(110));
alter table T_BSAMPLE_XLS rename column C_CASH_LOSS_REFUND to CASHLOSSRD;
alter table T_BSAMPLE_XLS modify (CASHLOSSRD varchar2(110));
alter table T_BSAMPLE_XLS rename column C_LOSS_RESERVE_RTD to LOSSRR;
alter table T_BSAMPLE_XLS modify (LOSSRR varchar2(110));
alter table T_BSAMPLE_XLS rename column C_LOSS_RESERVE_RLD to LOSSRR2;
alter table T_BSAMPLE_XLS modify (LOSSRR2 varchar2(110));
alter table T_BSAMPLE_XLS rename column C_LOSS_P_F_ENT to LOSSPFEND;
alter table T_BSAMPLE_XLS modify (LOSSPFEND varchar2(110));
alter table T_BSAMPLE_XLS rename column C_LOSS_P_F_WOA to LOSSPFWOA;
alter table T_BSAMPLE_XLS modify (LOSSPFWOA varchar2(110));
alter table T_BSAMPLE_XLS rename column C_INTEREST to INTEREST;
alter table T_BSAMPLE_XLS modify (INTEREST varchar2(110));
alter table T_BSAMPLE_XLS rename column C_TAX_ON to TAXON;
alter table T_BSAMPLE_XLS modify (TAXON varchar2(110));
alter table T_BSAMPLE_XLS rename column C_MISCELLANEOUS to MISCELLANEOUS;
alter table T_BSAMPLE_XLS modify (MISCELLANEOUS varchar2(110));
alter table T_BSAMPLE_XLS rename column C_PREMIUM_BALANCE to PMBL;
alter table T_BSAMPLE_XLS modify (PMBL varchar2(110));
alter table T_BSAMPLE_XLS rename column C_CLAIM_BALANCE to CMBL;
alter table T_BSAMPLE_XLS modify (CMBL varchar2(110));
alter table T_BSAMPLE_XLS rename column C_NET_BALANCE to NTBL;
alter table T_BSAMPLE_XLS modify (NTBL varchar2(110));
alter table T_BSAMPLE_XLS rename column C_YOUR_REF to CSCOSARFRNCNNT2;
alter table T_BSAMPLE_XLS modify (CSCOSARFRNCNNT2 varchar2(110));
